export { default as DashboardLayout } from './dashboard'
export { default as ExternalLayouts } from './external'
export { default as StudentLayout } from './studentLayout'
export { default as Container } from './container'
export { default as ResultBoard } from './resultBoard'
export { default as SubjectTemplate } from './subjectsTemplate'
